/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: farhad.Guli (https://sketchfab.com/farhad.Guli)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fifa-world-cup-ball-45b805a34787410296ac766a2de3aec4
Title: fifa world cup ball
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Balon = (props) => {
  const { nodes, materials } = useGLTF('/models/fifa_world_cup_ball.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.166}>
        <group position={[87.345, -10.86, -1.817]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2.geometry}
            material={materials.jabulani1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_1.geometry}
            material={materials.jabulani1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_2.geometry}
            material={materials.jabulani1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_3.geometry}
            material={materials.jabulani1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_4.geometry}
            material={materials.jabulani_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_5.geometry}
            material={materials.material}
          />
          <lineSegments
            geometry={nodes.Material2_6.geometry}
            material={materials.edge_color808080255}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/fifa_world_cup_ball.glb')
export default Balon;