/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const CHome = (props) => {
  const { nodes, materials } = useGLTF('/models/Home.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.779, 0.029, 0.25]} rotation={[-Math.PI / 2, 0, -0.773]} scale={0.007}>
        <group scale={0.1}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Plane002_Material_#411_0'].geometry}
            material={materials.Material_411}
            position={[191.118, 80.693, -23.511]}
            rotation={[0, 0, -Math.PI / 4]}
            scale={1.06}
          />
        </group>
      </group>
      <group
        position={[2.463, -0.178, -0.183]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={1.157}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group
            position={[-93.635, 156.583, -152.189]}
            rotation={[-Math.PI / 2, 0, 0.796]}
            scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubicle_Cubicle_Trim_0.geometry}
              material={materials['Cubicle_Trim.001']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubicle_Cubicle_Wall_0.geometry}
              material={materials['Cubicle_Wall.001']}
            />
          </group>
        </group>
      </group>
      <group position={[0.201, 0.712, -1.058]} rotation={[-Math.PI / 2, 0, 0.01]} scale={0.241}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-4.815, 1.463, -1.02]} scale={[0.438, 1, 1.09]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_17.geometry}
              material={materials.black}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_18.geometry}
              material={materials.blue_light}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_19.geometry}
              material={materials.Plastic}
            />
          </group>
          <group
            position={[-0.292, 0.814, -0.822]}
            rotation={[2.356, 0, -Math.PI / 2]}
            scale={[-0.235, -0.037, -0.235]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_21.geometry}
              material={materials.black}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_22.geometry}
              material={materials.blue}
            />
          </group>
          <group
            position={[-0.576, 0.474, -0.373]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={[-1.405, -0.024, -0.421]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_11.geometry}
              material={materials.blue_light}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_12.geometry}
              material={materials.black}
            />
          </group>
          <group position={[-0.335, 1.053, -2.055]} scale={[0.523, 0.1, 0.339]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_7.geometry}
              material={materials['7355608']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_8.geometry}
              material={materials.black}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_9.geometry}
              material={materials.blue_light}
            />
          </group>
          <group position={[1.071, 0.465, -0.414]} scale={[0.114, 0.107, 0.204]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_14.geometry}
              material={materials.black}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_15.geometry}
              material={materials.blue_light}
            />
          </group>
        </group>
      </group>
      <group position={[0.005, 0, -1.297]} rotation={[-Math.PI / 2, 0, -1.56]} scale={1.228}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <group position={[0.654, 1.254, 0.642]} scale={[0.019, 0.304, 0.013]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube004_MetalGalvanizedSteelWorn001_2K_0.geometry}
                material={materials.MetalGalvanizedSteelWorn001_2K}
                position={[-10.753, 0.007, 0]}
              />
            </group>
            <group
              position={[0.654, 1.254, 0.642]}
              rotation={[0, 0, -Math.PI / 2]}
              scale={[0.019, 0.481, 0.013]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube005_MetalGalvanizedSteelWorn001_2K_0.geometry}
                material={materials.MetalGalvanizedSteelWorn001_2K}
                position={[-0.752, -0.355, 0.116]}
                scale={[0.464, 0.464, 1]}
              />
            </group>
            <group
              position={[0.693, 0.645, 0.617]}
              rotation={[0, 0, Math.PI / 2]}
              scale={[0.019, 0.212, 0.013]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube006_MetalGalvanizedSteelWorn001_2K_0.geometry}
                material={materials.MetalGalvanizedSteelWorn001_2K}
                position={[-0.496, 1.001, 0]}
                scale={[0.998, 0.998, 1]}
              />
            </group>
            <group
              position={[0.693, 1.254, 0.642]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.019, 0.35, 0.013]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube009_MetalGalvanizedSteelWorn001_2K_0.geometry}
                material={materials.MetalGalvanizedSteelWorn001_2K}
                position={[-10.718, 0, -1.234]}
                scale={[1, 0.898, 1]}
              />
            </group>
            <group
              position={[0.693, 0.671, 0.642]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.019, 0.35, 0.013]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube010_MetalGalvanizedSteelWorn001_2K_0.geometry}
                material={materials.MetalGalvanizedSteelWorn001_2K}
                position={[-10.727, 0, 0.773]}
                scale={[1, 0.898, 1]}
              />
            </group>
            <group
              position={[-0.269, 1.254, 0.642]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.019, 0.35, 0.013]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube011_MetalGalvanizedSteelWorn001_2K_0.geometry}
                material={materials.MetalGalvanizedSteelWorn001_2K}
                scale={[1, 0.898, 1]}
              />
            </group>
            <group
              position={[-0.269, 0.671, 0.642]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.019, 0.35, 0.013]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube012_MetalGalvanizedSteelWorn001_2K_0.geometry}
                material={materials.MetalGalvanizedSteelWorn001_2K}
                scale={[1, 0.898, 1]}
              />
            </group>
            <group
              position={[-0.269, -0.595, 0.642]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.019, 0.35, 0.013]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube013_MetalGalvanizedSteelWorn001_2K_0.geometry}
                material={materials.MetalGalvanizedSteelWorn001_2K}
                scale={[1, 0.898, 1]}
              />
            </group>
            <group
              position={[0.308, -0.595, 0.642]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.019, 0.35, 0.013]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube014_MetalGalvanizedSteelWorn001_2K_0.geometry}
                material={materials.MetalGalvanizedSteelWorn001_2K}
                scale={[1, 0.898, 1]}
              />
            </group>
            <group
              position={[-0.269, -0.904, 0.642]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.019, 0.35, 0.013]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube019_MetalGalvanizedSteelWorn001_2K_0.geometry}
                material={materials.MetalGalvanizedSteelWorn001_2K}
                scale={[1, 0.898, 1]}
              />
            </group>
            <group
              position={[0.308, -0.904, 0.642]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.019, 0.35, 0.013]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube020_MetalGalvanizedSteelWorn001_2K_0.geometry}
                material={materials.MetalGalvanizedSteelWorn001_2K}
                scale={[1, 0.898, 1]}
              />
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_Wood005_0.geometry}
              material={materials['Wood.005']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube001_Wood005_0.geometry}
              material={materials['Wood.005']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube002_MetalGalvanizedSteelWorn001_2K_0.geometry}
              material={materials.MetalGalvanizedSteelWorn001_2K}
              position={[0.269, 1.248, 0.642]}
              scale={[0.019, 1.088, 0.013]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube003_MetalGalvanizedSteelWorn001_2K_0.geometry}
              material={materials.MetalGalvanizedSteelWorn001_2K}
              position={[-0.308, 1.248, 0.642]}
              scale={[0.019, 1.088, 0.013]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube007_MetalGalvanizedSteelWorn001_2K_0.geometry}
              material={materials.MetalGalvanizedSteelWorn001_2K}
              position={[0.308, -0.581, 0.642]}
              rotation={[0, 0, Math.PI / 2]}
              scale={[0.019, 0.308, 0.013]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube008_MetalGalvanizedSteelWorn001_2K_0.geometry}
              material={materials.MetalGalvanizedSteelWorn001_2K}
              position={[-0.05, 1.248, 0.642]}
              scale={[0.043, 0.934, 0.013]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube015_MetalGalvanizedSteelWorn001_2K_0.geometry}
              material={materials.MetalGalvanizedSteelWorn001_2K}
              position={[0.308, -0.595, 0.044]}
              rotation={[0, 0, Math.PI / 2]}
              scale={[0.013, 0.308, 0.013]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube017_MetalGalvanizedSteelWorn001_2K_0.geometry}
              material={materials.MetalGalvanizedSteelWorn001_2K}
              position={[-0.269, 0.645, 0.044]}
              scale={[0.019, 0.304, 0.013]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube018_MetalGalvanizedSteelWorn001_2K_0.geometry}
              material={materials.MetalGalvanizedSteelWorn001_2K}
              position={[0.308, -0.891, 0.642]}
              rotation={[0, 0, Math.PI / 2]}
              scale={[0.019, 0.308, 0.013]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube021_MetalGalvanizedSteelWorn001_2K_0.geometry}
              material={materials.MetalGalvanizedSteelWorn001_2K}
              position={[0.308, -0.904, 0.044]}
              rotation={[0, 0, Math.PI / 2]}
              scale={[0.013, 0.308, 0.013]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube022_MetalGalvanizedSteelWorn001_2K_0.geometry}
              material={materials.MetalGalvanizedSteelWorn001_2K}
              position={[0.308, -0.595, 0.388]}
              rotation={[0, 0, Math.PI / 2]}
              scale={[0.013, 0.308, 0.013]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube023_MetalGalvanizedSteelWorn001_2K_0.geometry}
              material={materials.MetalGalvanizedSteelWorn001_2K}
              position={[0.308, -0.904, 0.388]}
              rotation={[0, 0, Math.PI / 2]}
              scale={[0.013, 0.308, 0.013]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube024_Wood005_0.geometry}
              material={materials['Wood.005']}
              scale={[0.993, 1, 1]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube025_Wood005_0.geometry}
              material={materials['Wood.005']}
              scale={[0.99, 1, 1]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube026_Wood005_0.geometry}
              material={materials['Wood.005']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube027_MetalGalvanizedSteelWorn001_2K_0.geometry}
              material={materials.MetalGalvanizedSteelWorn001_2K}
              position={[-0.286, 0.071, 0.742]}
              scale={[0.008, 0.317, 0.005]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube028_MetalGalvanizedSteelWorn001_2K_0.geometry}
              material={materials.MetalGalvanizedSteelWorn001_2K}
              position={[-0.151, 0.071, 0.742]}
              scale={[0.008, 0.317, 0.005]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube029_MetalGalvanizedSteelWorn001_2K_0.geometry}
              material={materials.MetalGalvanizedSteelWorn001_2K}
              position={[-0.286, -0.246, 0.752]}
              rotation={[0, 0, -Math.PI / 2]}
              scale={[0.007, 0.075, 0.005]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube030_MetalGalvanizedSteelWorn001_2K_0.geometry}
              material={materials.MetalGalvanizedSteelWorn001_2K}
              position={[-0.286, 0.374, 0.752]}
              rotation={[0, 0, -Math.PI / 2]}
              scale={[0.007, 0.075, 0.005]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube031_MetalGalvanizedSteelWorn001_2K_0.geometry}
              material={materials.MetalGalvanizedSteelWorn001_2K}
              position={[-0.286, -0.246, 0.678]}
              rotation={[0, 0, -Math.PI / 2]}
              scale={[0.007, 0.075, 0.005]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube032_MetalGalvanizedSteelWorn001_2K_0.geometry}
              material={materials.MetalGalvanizedSteelWorn001_2K}
              position={[-0.286, 0.374, 0.678]}
              rotation={[0, 0, -Math.PI / 2]}
              scale={[0.007, 0.075, 0.005]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube033_MetalGalvanizedSteelWorn001_2K_0.geometry}
              material={materials.MetalGalvanizedSteelWorn001_2K}
              position={[-0.286, -0.239, 0.752]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[0.007, 0.041, 0.005]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube034_MetalGalvanizedSteelWorn001_2K_0.geometry}
              material={materials.MetalGalvanizedSteelWorn001_2K}
              position={[-0.144, -0.239, 0.752]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[0.007, 0.041, 0.005]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube035_MetalGalvanizedSteelWorn001_2K_0.geometry}
              material={materials.MetalGalvanizedSteelWorn001_2K}
              position={[-0.286, 0.381, 0.752]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[0.007, 0.041, 0.005]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube036_MetalGalvanizedSteelWorn001_2K_0.geometry}
              material={materials.MetalGalvanizedSteelWorn001_2K}
              position={[-0.144, 0.381, 0.752]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[0.007, 0.041, 0.005]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube037_Cloth_pattern_0.geometry}
              material={materials.Cloth_pattern}
              position={[-0.048, 0.065, 0.67]}
              scale={[0.152, 0.394, 0.001]}
            />
          </group>
        </group>
      </group>
      <group position={[1.342, 0.821, -1.341]} rotation={[-Math.PI / 2, 0, 0]} scale={0.003}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_10.geometry}
          material={materials['08___Default']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_11001.geometry}
          material={materials['09___Default']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.Material__27}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials['01___Default']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4001.geometry}
          material={materials['02___Default']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.wire_000000000}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.wire_018018018}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7001.geometry}
          material={materials.wire_028028177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8001.geometry}
          material={materials['03___Default']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9001.geometry}
          material={materials['07___Default']}
        />
      </group>
      <group position={[0.837, 0.817, -1.514]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node_117540_Material_0_0.geometry}
          material={materials.Material_0}
          rotation={[Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[0.886, 1.014, -1.74]} rotation={[-Math.PI / 2, 0, 0]} scale={0.006}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2001.geometry}
          material={materials.material_frame}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3001.geometry}
          material={materials.material_poster}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4002.geometry}
          material={materials.material_matting}
        />
      </group>
      <group position={[-0.466, 0.944, -1.727]} rotation={[-Math.PI / 2, 0, 0.005]} scale={0.007}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2002.geometry}
          material={materials['material_frame.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3002.geometry}
          material={materials['material_poster.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4003.geometry}
          material={materials['material_matting.001']}
        />
      </group>
      <group position={[0.164, 0.019, -0.867]} rotation={[-Math.PI / 2, 0, -1.222]} scale={1.057}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Material5-material-material'].geometry}
          material={materials['Material5-material']}
          position={[0.012, 0.001, 0.528]}
          rotation={[0, 0, 2.779]}
          scale={[0.732, 0.744, 1.066]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Material0-material-material'].geometry}
          material={materials['Material0-material']}
          position={[0.012, 0.001, 0.528]}
          rotation={[0, 0, 2.779]}
          scale={[0.732, 0.744, 1.066]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Material1-material-material'].geometry}
          material={materials['Material1-material']}
          position={[0.012, 0.001, 0.528]}
          rotation={[0, 0, 2.779]}
          scale={[0.732, 0.744, 1.066]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Material2-material-material'].geometry}
          material={materials['Material2-material']}
          position={[0.012, 0.001, 0.528]}
          rotation={[0, 0, 2.779]}
          scale={[0.732, 0.744, 1.066]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Material3-material-material'].geometry}
          material={materials['Material3-material']}
          position={[0.012, 0.001, 0.528]}
          rotation={[0, 0, 2.779]}
          scale={[0.732, 0.744, 1.066]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Material4-material-material'].geometry}
          material={materials['Material4-material']}
          position={[0.012, 0.001, 0.528]}
          rotation={[0, 0, 2.779]}
          scale={[0.732, 0.744, 1.066]}
        />
      </group>
      <group position={[-1.244, 0.217, 3.704]} rotation={[-Math.PI / 2, 0, -3.138]} scale={0.372}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-1.136, 1.792, 8.258]} scale={[0.715, 2.333, 0.668]}>
            <group position={[-0.083, -0.776, 0.009]} scale={[0.91, 0.179, 0.962]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_6001.geometry}
                material={materials['Material.040']}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_7002.geometry}
                material={materials['Material.041']}
              />
            </group>
            <group position={[-0.083, -0.3, 0.009]} scale={[0.91, 0.179, 0.962]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_11002.geometry}
                material={materials['Material.040']}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_12001.geometry}
                material={materials['Material.041']}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_13.geometry}
                material={materials['Material.036']}
              />
            </group>
            <group position={[-0.083, 0.19, 0.009]} scale={[0.91, 0.179, 0.962]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_17001.geometry}
                material={materials['Material.040']}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_18001.geometry}
                material={materials['Material.041']}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_19001.geometry}
                material={materials['Material.036']}
              />
            </group>
            <group position={[-0.083, 0.694, 0.009]} scale={[0.91, 0.179, 0.962]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_23.geometry}
                material={materials['Material.040']}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_24.geometry}
                material={materials['Material.041']}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_25.geometry}
                material={materials['Material.036']}
              />
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_4004.geometry}
              material={materials['Material.036']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_9002.geometry}
              material={materials['Material.036']}
              position={[-1.008, -0.843, 0.042]}
              rotation={[Math.PI, 0, -Math.PI / 2]}
              scale={[-0.016, -0.013, -0.409]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_15001.geometry}
              material={materials['Material.036']}
              position={[-1.008, -0.368, 0.042]}
              rotation={[Math.PI, 0, -Math.PI / 2]}
              scale={[-0.016, -0.013, -0.409]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_21001.geometry}
              material={materials['Material.036']}
              position={[-1.008, 0.122, 0.042]}
              rotation={[Math.PI, 0, -Math.PI / 2]}
              scale={[-0.016, -0.013, -0.409]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_27.geometry}
              material={materials['Material.036']}
              position={[-1.008, 0.626, 0.042]}
              rotation={[Math.PI, 0, -Math.PI / 2]}
              scale={[-0.016, -0.013, -0.409]}
            />
          </group>
        </group>
      </group>
      <group position={[1.18, 0.016, -1.178]} rotation={[-Math.PI / 2, 0, 0]} scale={0.158}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_4005.geometry}
            material={materials['Material.042']}
            scale={[1, 0.873, 1]}
          />
        </group>
      </group>
      <group position={[-2.689, 0.247, 0.159]} scale={0.021}>
        <group position={[87.345, -10.86, -1.817]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2.geometry}
            material={materials.jabulani1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2001.geometry}
            material={materials.jabulani1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2002.geometry}
            material={materials.jabulani1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2003.geometry}
            material={materials.jabulani1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2004.geometry}
            material={materials.jabulani_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2005.geometry}
            material={materials['material.001']}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Home.glb')
export default CHome
