/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: TheLastOfUsPlayer (https://sketchfab.com/TheLastOfUsPlayer)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stack-of-ps4-games-ef6f4e2c96c44fb6a394da5e27db7118
Title: Stack of PS4 Games
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const JuegosPS4 = (props) => {
  const { nodes, materials } = useGLTF('/models/stack_of_ps4_games.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Node_117540_Material_0_0.geometry}
        material={materials.Material_0}
      />
    </group>
  )
}

useGLTF.preload('/models/stack_of_ps4_games.glb')
export default JuegosPS4