/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: assetfactory (https://sketchfab.com/assetfactory)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/record-player-for-vinyls-52104c38e5c843bd9405445b2fe4a30b
Title: Record player for vinyls
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const MesaVinilo = (props) => {
  const { nodes, materials } = useGLTF('/models/record_player_for_vinyls.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube_TapeRecorder_0.geometry}
        material={materials.TapeRecorder}
        position={[0, -3.389, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder_TapeRecorder_0.geometry}
        material={materials.TapeRecorder}
        position={[-21.75, 26.749, 6.419]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001_TapeRecorder_0.geometry}
        material={materials.TapeRecorder}
        position={[-21.75, 22.46, 6.419]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[118.377, 118.377, 100]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001_TapeRecorder_0.geometry}
        material={materials.TapeRecorder}
        position={[8.281, 41.193, 47.666]}
        rotation={[-Math.PI / 2, 0, 0.493]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002_TapeRecorder_0.geometry}
        material={materials.TapeRecorder}
        position={[43.036, 41.633, -3.691]}
        rotation={[0.005, -0.555, 0.002]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder003_TapeRecorder_0.geometry}
        material={materials.TapeRecorder}
        position={[78.487, 18.668, 46.933]}
        rotation={[-1.356, 0, Math.PI / 2]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_TapeRecorder_0.geometry}
        material={materials.TapeRecorder}
        position={[0, -3.389, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder005_TapeRecorder_0.geometry}
        material={materials.TapeRecorder}
        position={[-21.75, 29.261, 6.419]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003_TapeRecorder_0.geometry}
        material={materials.TapeRecorder}
        position={[63.552, 26.749, 40.558]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004_TapeRecorder_0.geometry}
        material={materials.TapeRecorder}
        position={[67.456, 36.341, 40.558]}
        rotation={[-Math.PI / 2, 0.541, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder010_TapeRecorder_0.geometry}
        material={materials.TapeRecorder}
        position={[71.87, 28.935, -49.11]}
        rotation={[-Math.PI / 2, 0, 0.511]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder007_TapeRecorder_0.geometry}
        material={materials.TapeRecorder}
        position={[73.545, 19.715, -19.625]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005_Glass_0.geometry}
        material={materials.Glass}
        position={[0, 49.147, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube006_TapeRecorder_0.geometry}
        material={materials.TapeRecorder}
        position={[77.469, 22.694, -101.35]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder008_TapeRecorder_0.geometry}
        material={materials.TapeRecorder}
        position={[65.937, 19.749, 60.377]}
        rotation={[-Math.PI / 2, 0, 0.101]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder004_TapeRecorder_0.geometry}
        material={materials.TapeRecorder}
        position={[-77.412, 19.749, 60.047]}
        rotation={[-Math.PI / 2, 0, -0.282]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube007_TapeRecorder_0.geometry}
        material={materials.TapeRecorder}
        position={[78.487, 19.569, 44.34]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
    </group>
  )
}

useGLTF.preload('/models/record_player_for_vinyls.glb')
export default MesaVinilo