/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Mehdi Shahsavan (https://sketchfab.com/ahmagh2e)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/office-desk-7-mb-18abda12d33b4231aa13f92a291c717e
Title: Office Desk_7_MB
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const MesaOficina = (props) => {
  const { nodes, materials } = useGLTF('/models/office_desk_7_mb.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['01_01_0'].geometry}
          material={materials.material}
          position={[-70.653, 91.451, -25.536]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['02_02_0'].geometry}
          material={materials.material_1}
          position={[-63.615, 29.63, 152.957]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/office_desk_7_mb.glb')
export default MesaOficina;