/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Portatil = (props) => {
  const { nodes, materials } = useGLTF('/models/laptop.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-1.556, 0, 0]} scale={17.536}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.Body_BAKED}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.Internals_BAKED}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.Internals_BAKED}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.Keys_BAKED}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.Screen_under_glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials['Top_Lid.002_BAKED']}
        />
      </group>
    </group>
  )
}
useGLTF.preload('/models/laptop.glb')
export default Portatil