/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Akulla (https://sketchfab.com/Akula3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ps4-5709d878c76f4a799cd9e36eb858a06b
Title: PS4
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const PS4 = (props) => {
  const { nodes, materials } = useGLTF('/models/ps4.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.playstation4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.ps4_light}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/ps4.glb')
export default PS4