/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: albertduranll (https://sketchfab.com/albertduranll)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ps4-controller-c10e207b60ec451fabde91c17d4cb2ac
Title: PS4 Controller
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const PS4Mando = (props) => {
  const { nodes, materials } = useGLTF('/models/ps4_controller.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cylinder_Default_0.geometry}
        material={materials.Default}
      />
    </group>
  )
}

useGLTF.preload('/models/ps4_controller.glb')
export default PS4Mando