/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: ℜ𝔢𝔞𝔩 𝔖𝔩𝔦𝔪 𝔖𝔥𝔞𝔡𝔶 (https://sketchfab.com/real_slimshady)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/office-desk-chair-e3d038bac16740fb875c00450a13af1b
Title: Office Desk Chair
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Silla = (props) => {
  const { nodes, materials } = useGLTF('/models/office_desk_chair.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Material5-material-material'].geometry}
          material={materials['Material5-material']}
          position={[0.012, 0.001, 0.528]}
          rotation={[0, 0, 2.779]}
          scale={[0.732, 0.744, 1.066]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Material0-material-material'].geometry}
          material={materials['Material0-material']}
          position={[0.012, 0.001, 0.528]}
          rotation={[0, 0, 2.779]}
          scale={[0.732, 0.744, 1.066]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Material1-material-material'].geometry}
          material={materials['Material1-material']}
          position={[0.012, 0.001, 0.528]}
          rotation={[0, 0, 2.779]}
          scale={[0.732, 0.744, 1.066]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Material2-material-material'].geometry}
          material={materials['Material2-material']}
          position={[0.012, 0.001, 0.528]}
          rotation={[0, 0, 2.779]}
          scale={[0.732, 0.744, 1.066]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Material3-material-material'].geometry}
          material={materials['Material3-material']}
          position={[0.012, 0.001, 0.528]}
          rotation={[0, 0, 2.779]}
          scale={[0.732, 0.744, 1.066]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Material4-material-material'].geometry}
          material={materials['Material4-material']}
          position={[0.012, 0.001, 0.528]}
          rotation={[0, 0, 2.779]}
          scale={[0.732, 0.744, 1.066]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/office_desk_chair.glb')
export default Silla