/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Andrew Jepson (https://sketchfab.com/ajepson)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/checkered-tile-floor-e6c5ea5c0c8f4c9ba27f07dcb9091ffd
Title: Checkered Tile Floor
*/
import * as THREE from 'three';
import React, { useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";

const Suelo = (props) => {
  const { nodes, materials } = useGLTF("/models/checkered_tile_floor.glb");

  const { floorTexture } = useTexture({
    floorTexture: "/textures/clean-white-wall.jpg",
  });

  // Asegúrate de configurar estos parámetros
  floorTexture.wrapS = floorTexture.wrapT = THREE.RepeatWrapping; // Permitir que se repita
  floorTexture.anisotropy = 16; // Mejorar la calidad de la textura (si la GPU lo permite)

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.floor_texture}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <meshLambertMaterial map={floorTexture} />
      </mesh>
    </group>
  );
};

useGLTF.preload("/models/checkered_tile_floor.glb");
export default Suelo;
