/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Qu3st10n (https://sketchfab.com/Qu3st10n)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/coffee-table-9ae8fb70158e4b68bbd5abd6e57f66f3
Title: Coffee Table
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Table = (props) => {
  const { nodes, materials } = useGLTF('/models/coffee_table.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.007, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.CoffeeTable_CoffeeTable_mat_0.geometry}
          material={materials.CoffeeTable_mat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.proxy_CoffeeTable_proxy_0.geometry}
          material={materials.proxy}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/coffee_table.glb')
export default Table